#TWITTER
APP_KEY = ""
APP_SECRET = ""
OATH_TOKEN = ""
OATH_TOKEN_SECRET = ""
#BIGQUERY
BIGQUERY_PROJECT_NAME = ""
BIGQUERY_DATESET = ""
BIGQUERY_TABLE = ""
BIGQUERY_QUERY_TABLE = "`"+BIGQUERY_PROJECT_NAME+"."+BIGQUERY_DATESET+"."+BIGQUERY_TABLE+"`"
#SERVICE ACCOUNT
GCP_SERVICE_ACCOUNT_JSON = '';
#SEARCH
HASHTAG = ""